services:
  db:
    image: postgres:16-alpine
    container_name: tabularium-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tabularium_db
      POSTGRES_USER: dms
      POSTGRES_PASSWORD: dms
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: tabularium_pgdata
#    external: true
